spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:trading;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.neueda.leap: INFO
